/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontWeight: {
        semiBold: "500",
        bold: "600",
      },
      colors: {
        primary: {
          regular: "#1C3B7D",
          dark: "#f6f6f6",
          darker: "#010E35",
          lightest: "#E6EDF7",
          lighter: "#D2DEE5",
          light: "#B9C8D8",
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        gray: {
          10: "#F6F6F6",
          20: "#E1E1E1",
          regular: "#808080",
          dark: "#464646",
          darker: "#282828",
          fade: "#C9C9C9",
          "-10": "#0A0A0A",
          "-20": "#151515",
        },
        success: {
          10: "#F0FCDE",
          20: "#E1F59E",
          regular: "#8CEF1C",
          dark: "#5A7510",
          darker: "#395102",
          fade: "#B0E672",
          "-10": "#111D03",
          "-20": "#122306",
        },
        warning: {
          10: "#FDF4DE",
          20: "#F7DFAC",
          regular: "#E4B01D",
          dark: "#A67301",
          darker: "#573F02",
          fade: "#F1C670",
          "-10": "#181401",
          "-20": "#322800",
        },
        error: {
          10: "#FEECEE",
          20: "#FEC5C5",
          regular: "#E73436",
          dark: "#A02D1C",
          darker: "#612202",
          fade: "#F79595",
          "-10": "#260101",
          "-20": "#320D0D",
        },
        info: {
          10: "#F2FAFF",
          20: "#B0E7F1",
          regular: "#2F56FB",
          dark: "#2B4557",
          darker: "#001928",
          fade: "#81E8E8",
          "-10": "#111A23",
          "-20": "#171C33",
        },
        surface: {
          body: "#FAFAFA",
          foreground: "#FFFFFF",
          "dim-s": "#D1D1D1",
          "dim-m": "#A8A8A8",
          "dim-l": "#858585",
          positive: "#FFFFFF",
          negative: "#000000",
        },
        static: {
          light: "#FFFFFF",
          muted: "#858585",
          dark: "#000000",
        },
        text: {
          regular: "#222222",
          muted: "#555555",
          fade: "#969696",
          positive: "#FFFFFF",
          negative: "#000000",
        },
        border: "hsl(var(--border))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
